const users = [{
  id: 200,
  first_name: 'ukundwa',
  last_name: 'dia',
  email: 'dia@gmail.com',
  address: 'kamembe',
  password: '200',
  phoneNumber: '0780000092',
  is_admin: true,
},
{
  id: 201,
  first_name: 'tuy',
  last_name: 'eric',
  email: 'eric@gmail.com',
  address: 'kamembe',
  password: '100',
  phoneNumber: '078229862',
  is_admin: false,
},
{
  id: 202,
  first_name: 'ira',
  last_name: 'vivi',
  email: 'vivi@gmail.com',
  address: 'kamembe',
  password: '100',
  phoneNumber: '0782237192',
  is_admin: false,
},
{
  id: 203,
  first_name: 'turi',
  last_name: 'Eli',
  email: 'eli@gmail.com',
  address: 'kamembe',
  password: '100',
  phoneNumber: '078874592',
  is_admin: false,
}];

export default users;
